[project]
name = "build_env_amp_gen"
version = "0.1.0"
authors = ["Cheryl Pappenheimer <cheryl.theroux@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
root = ">=6.32.0,<6.33"
boost-cpp = ">=1.85.0,<1.86"
openmp = ">=8.0.1,<8.1"
cmake = ">=3.29.6,<3.30"

[activation]
scripts = ["env_setup.sh"]

[system-requirements]
linux="3.10"